version: '3.8'

services:
  # Model Server (vLLM) - Integrated from xCodeAgent01
  model-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.model-server
    ports:
      - "8000:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - VLLM_HOST=0.0.0.0
      - VLLM_PORT=8000
      - MODEL_NAME=${MODEL_NAME:-microsoft/DialoGPT-medium}
      - GPU_MEMORY_UTILIZATION=0.8
      - MAX_MODEL_LEN=2048
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Redis for caching and pub/sub
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # reVoAgent Core Platform
  revoagent-core:
    build:
      context: .
      dockerfile: docker/Dockerfile.core
    ports:
      - "12000:12000"
    environment:
      - REVO_AGENT_HOST=0.0.0.0
      - REVO_AGENT_PORT=12000
      - MODEL_SERVER_HOST=model-server
      - MODEL_SERVER_PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WORKSPACE_DIR=/app/workspace
      - LOG_LEVEL=INFO
      - PYTHONPATH=/app/OpenHands:/app/src
    volumes:
      - ./workspace:/app/workspace
      - ./config:/app/config
      - ./logs:/app/logs
      - ./OpenHands:/app/OpenHands:ro
    depends_on:
      model-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # OpenHands Integration Service
  openhands-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.openhands
    ports:
      - "3000:3000"
    environment:
      - OPENHANDS_HOST=0.0.0.0
      - OPENHANDS_PORT=3000
      - WORKSPACE_DIR=/app/workspace
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.41-nikolaik
      - LOG_ALL_EVENTS=true
    volumes:
      - ./workspace:/app/workspace
      - ./OpenHands:/app/OpenHands
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - revoagent-core
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Web Dashboard (Enhanced from xCodeAgent01)
  web-dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile.dashboard
    ports:
      - "3001:3001"
    environment:
      - DASHBOARD_HOST=0.0.0.0
      - DASHBOARD_PORT=3001
      - REVOAGENT_API_URL=http://revoagent-core:12000
      - OPENHANDS_API_URL=http://openhands-service:3000
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - revoagent-core
      - openhands-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Monitoring and Metrics
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - revoagent-core
      - web-dashboard
      - openhands-service
    restart: unless-stopped

volumes:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16