# Three-Engine Architecture Configuration
# reVoAgent Engine Configuration

engines:
  # 🔵 Perfect Recall Engine - Memory and Context Management
  perfect_recall:
    enabled: true
    
    # Memory Configuration
    memory_limit: "4GB"
    retrieval_timeout: "100ms"
    context_window: 32000
    persistence: true
    
    # Storage Settings
    storage:
      type: "hybrid"  # memory, disk, hybrid
      compression: true
      encryption: true
      backup_interval: "1h"
    
    # Performance Tuning
    performance:
      cache_size: "1GB"
      index_type: "vector"
      similarity_threshold: 0.85
      max_concurrent_queries: 10
    
    # Context Management
    context:
      session_timeout: "24h"
      project_context: true
      conversation_history: true
      code_context_depth: 5

  # 🟣 Parallel Mind Engine - Multi-threaded Processing
  parallel_mind:
    enabled: true
    
    # Worker Configuration
    min_workers: 4
    max_workers: 16
    scaling_threshold: 0.8
    worker_timeout: "30s"
    
    # Load Balancing
    load_balancing:
      strategy: "intelligent"  # round_robin, least_loaded, intelligent
      health_check_interval: "10s"
      failure_threshold: 3
      recovery_timeout: "60s"
    
    # Task Management
    task_management:
      queue_size: 1000
      priority_levels: 5
      task_timeout: "300s"
      retry_attempts: 3
    
    # Resource Management
    resources:
      cpu_limit: "80%"
      memory_per_worker: "512MB"
      disk_space_limit: "10GB"
      network_bandwidth: "100MB/s"

  # 🩷 Creative Engine - Innovation and Solution Generation
  creative_engine:
    enabled: true
    
    # Creativity Configuration
    solution_count: 5
    creativity_level: 0.8
    innovation_bias: 0.6
    learning_rate: 0.1
    
    # Solution Generation
    generation:
      diversity_threshold: 0.7
      novelty_weight: 0.4
      practicality_weight: 0.6
      exploration_rate: 0.3
    
    # Innovation Metrics
    innovation:
      scoring_algorithm: "composite"
      baseline_comparison: true
      trend_analysis: true
      breakthrough_detection: true
    
    # Learning and Adaptation
    learning:
      feedback_integration: true
      pattern_recognition: true
      solution_evolution: true
      success_tracking: true

# Engine Coordination
coordination:
  # Inter-engine Communication
  communication:
    protocol: "websocket"
    timeout: "5s"
    retry_attempts: 3
    heartbeat_interval: "30s"
  
  # Task Distribution
  distribution:
    strategy: "optimal"  # round_robin, capability_based, optimal
    load_balancing: true
    failover: true
    redundancy: false
  
  # Result Synthesis
  synthesis:
    aggregation_method: "weighted"
    confidence_weighting: true
    consensus_threshold: 0.7
    conflict_resolution: "voting"

# Monitoring and Logging
monitoring:
  enabled: true
  
  # Metrics Collection
  metrics:
    performance: true
    resource_usage: true
    error_rates: true
    response_times: true
  
  # Logging Configuration
  logging:
    level: "INFO"  # DEBUG, INFO, WARNING, ERROR
    format: "structured"
    rotation: "daily"
    retention: "30d"
  
  # Alerting
  alerting:
    enabled: true
    thresholds:
      response_time: "1s"
      error_rate: "5%"
      memory_usage: "90%"
      cpu_usage: "85%"

# Security Configuration
security:
  # Engine Isolation
  isolation:
    enabled: true
    sandbox_mode: true
    resource_limits: true
    network_isolation: true
  
  # Access Control
  access_control:
    authentication: true
    authorization: true
    api_key_required: false
    rate_limiting: true
  
  # Data Protection
  data_protection:
    encryption_at_rest: true
    encryption_in_transit: true
    data_anonymization: false
    audit_logging: true