# Staging Environment Configuration
# Production-like environment for testing and validation

environment: staging
debug: false
log_level: INFO

# Database Configuration
database:
  host: ${DB_HOST:-staging-db.revoagent.com}
  port: ${DB_PORT:-5432}
  name: ${DB_NAME:-revoagent_staging}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  pool_size: 10
  max_overflow: 20
  echo: false
  ssl_mode: require

# Redis Configuration
redis:
  host: ${REDIS_HOST:-staging-redis.revoagent.com}
  port: ${REDIS_PORT:-6379}
  db: 0
  password: ${REDIS_PASSWORD}
  max_connections: 50
  ssl: true

# AI Model Configuration
ai_models:
  default_provider: local
  local_models:
    - name: deepseek-r1
      path: /app/models/deepseek-r1
      enabled: true
      max_memory: 8GB
    - name: llama-3.2
      path: /app/models/llama-3.2
      enabled: true
      max_memory: 6GB
  
  cloud_fallback:
    enabled: true
    providers:
      openai:
        api_key: ${OPENAI_API_KEY}
        model: gpt-4
        rate_limit: 100
      anthropic:
        api_key: ${ANTHROPIC_API_KEY}
        model: claude-3-sonnet
        rate_limit: 50

# Agent Configuration
agents:
  max_concurrent_tasks: 10
  task_timeout: 600
  heartbeat_interval: 30
  auto_restart: true
  debug_mode: false
  resource_limits:
    memory: 2GB
    cpu: 1.0

# WebSocket Configuration
websocket:
  host: 0.0.0.0
  port: 8080
  max_connections: 500
  heartbeat_interval: 30
  message_size_limit: 1048576  # 1MB
  compression: true

# Security Configuration
security:
  jwt_secret: ${JWT_SECRET}
  jwt_expiry: 3600  # 1 hour
  cors_origins:
    - https://staging.revoagent.com
    - https://staging-app.revoagent.com
  rate_limiting:
    enabled: true
    requests_per_minute: 100
    burst_size: 20
  
  ssl:
    enabled: true
    cert_path: /etc/ssl/certs/staging.crt
    key_path: /etc/ssl/private/staging.key
  
  authentication:
    session_timeout: 3600
    max_login_attempts: 5
    lockout_duration: 900  # 15 minutes

# Monitoring Configuration
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_interval: 30
  log_requests: true
  detailed_metrics: true
  
  prometheus:
    enabled: true
    scrape_interval: 15s
  
  grafana:
    enabled: true
    admin_password: ${GRAFANA_ADMIN_PASSWORD}
  
  alerting:
    enabled: true
    webhook_url: ${ALERT_WEBHOOK_URL}
    email_notifications: true

# File Storage
storage:
  type: s3
  bucket: revoagent-staging-storage
  region: us-east-1
  access_key: ${AWS_ACCESS_KEY_ID}
  secret_key: ${AWS_SECRET_ACCESS_KEY}
  max_file_size: 52428800  # 50MB
  encryption: true
  versioning: true

# External Integrations
integrations:
  github:
    enabled: true
    api_token: ${GITHUB_TOKEN}
    webhook_secret: ${GITHUB_WEBHOOK_SECRET}
    rate_limit: 5000
  
  slack:
    enabled: true
    bot_token: ${SLACK_BOT_TOKEN}
    signing_secret: ${SLACK_SIGNING_SECRET}
    channels:
      alerts: staging-alerts
      deployments: staging-deployments
  
  jira:
    enabled: true
    url: ${JIRA_URL}
    username: ${JIRA_USERNAME}
    api_token: ${JIRA_API_TOKEN}
    project_key: REVO

# Performance Settings
performance:
  cache_ttl: 1800  # 30 minutes
  request_timeout: 60
  max_request_size: 52428800  # 50MB
  worker_processes: 4
  worker_threads: 8
  
  auto_scaling:
    enabled: true
    min_replicas: 2
    max_replicas: 10
    target_cpu: 70
    target_memory: 80

# Backup Configuration
backup:
  enabled: true
  interval: daily
  retention_days: 30
  storage_type: s3
  bucket: revoagent-staging-backups
  encryption: true
  
  schedule:
    database: "0 2 * * *"  # 2 AM daily
    files: "0 3 * * *"     # 3 AM daily

# Logging Configuration
logging:
  level: INFO
  format: json
  rotation: daily
  retention_days: 30
  
  destinations:
    - type: file
      path: /var/log/revoagent/app.log
    - type: elasticsearch
      host: ${ELASTICSEARCH_HOST}
      index: revoagent-staging-logs
    - type: cloudwatch
      log_group: /aws/revoagent/staging

# Testing Configuration
testing:
  smoke_tests: true
  performance_tests: true
  security_tests: true
  
  test_data:
    enabled: true
    refresh_interval: daily
  
  load_testing:
    max_concurrent_users: 100
    test_duration: 300  # 5 minutes

# Deployment Configuration
deployment:
  strategy: blue_green
  health_check_path: /health
  readiness_probe_delay: 30
  liveness_probe_delay: 60
  
  rollback:
    enabled: true
    automatic: true
    failure_threshold: 5
  
  canary:
    enabled: false
    traffic_percentage: 10
    duration: 600  # 10 minutes