global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'revoagent-production'
    environment: 'production'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # reVoAgent Backend instances
  - job_name: 'revoagent-backend'
    static_configs:
      - targets: 
          - 'backend-1:12001'
          - 'backend-2:12001'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # NGINX Load Balancer
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    metrics_path: '/nginx_status'
    scrape_interval: 15s

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  # PostgreSQL monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Application health checks
  - job_name: 'revoagent-health'
    static_configs:
      - targets: 
          - 'backend-1:12001'
          - 'backend-2:12001'
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Frontend monitoring (if metrics available)
  - job_name: 'revoagent-frontend'
    static_configs:
      - targets: ['frontend-1:12000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    honor_labels: true

  # Docker container metrics (if cAdvisor is available)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    honor_labels: true