groups:
  # Critical System Alerts
  - name: critical_system_alerts
    rules:
      # Backend API Down
      - alert: BackendAPIDown
        expr: up{job="revoagent-backend"} == 0
        for: 30s
        labels:
          severity: critical
          service: backend
        annotations:
          summary: "reVoAgent Backend API is down"
          description: "Backend instance {{ $labels.instance }} has been down for more than 30 seconds"

      # High Error Rate
      - alert: HighErrorRate
        expr: rate(revoagent_requests_total{status=~"5.."}[5m]) / rate(revoagent_requests_total[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
          service: backend
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for endpoint {{ $labels.endpoint }}"

      # High Response Time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(revoagent_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: backend
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s for {{ $labels.endpoint }}"

      # Circuit Breaker Open
      - alert: CircuitBreakerOpen
        expr: revoagent_circuit_breaker_state > 0.5
        for: 1m
        labels:
          severity: critical
          service: backend
        annotations:
          summary: "Circuit breaker is open"
          description: "Circuit breaker {{ $labels.name }} is open, indicating service degradation"

  # Resource Alerts
  - name: resource_alerts
    rules:
      # High CPU Usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value }}% on {{ $labels.instance }}"

      # High Disk Usage
      - alert: HighDiskUsage
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 90
        for: 5m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "High disk usage detected"
          description: "Disk usage is {{ $value }}% on {{ $labels.instance }} for {{ $labels.mountpoint }}"

  # Database Alerts
  - name: database_alerts
    rules:
      # Redis Down
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 30s
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis is down"
          description: "Redis instance {{ $labels.instance }} is not responding"

      # PostgreSQL Down
      - alert: PostgreSQLDown
        expr: up{job="postgres"} == 0
        for: 30s
        labels:
          severity: critical
          service: postgres
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL instance {{ $labels.instance }} is not responding"

      # High Database Connections
      - alert: HighDatabaseConnections
        expr: pg_stat_database_numbackends / pg_settings_max_connections > 0.8
        for: 5m
        labels:
          severity: warning
          service: postgres
        annotations:
          summary: "High database connection usage"
          description: "Database connection usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"

  # Application Alerts
  - name: application_alerts
    rules:
      # AI Model Failures
      - alert: AIModelFailures
        expr: increase(revoagent_ai_model_failures_total[5m]) > 5
        for: 2m
        labels:
          severity: warning
          service: ai_models
        annotations:
          summary: "High AI model failure rate"
          description: "{{ $value }} AI model failures in the last 5 minutes"

      # WebSocket Connection Issues
      - alert: WebSocketConnectionDrop
        expr: decrease(revoagent_active_connections[5m]) > 10
        for: 2m
        labels:
          severity: warning
          service: websocket
        annotations:
          summary: "High WebSocket connection drop rate"
          description: "{{ $value }} WebSocket connections dropped in the last 5 minutes"

      # Cache Miss Rate High
      - alert: HighCacheMissRate
        expr: rate(revoagent_cache_misses_total[5m]) / (rate(revoagent_cache_hits_total[5m]) + rate(revoagent_cache_misses_total[5m])) > 0.8
        for: 10m
        labels:
          severity: warning
          service: cache
        annotations:
          summary: "High cache miss rate"
          description: "Cache miss rate is {{ $value | humanizePercentage }}"

  # External Service Alerts
  - name: external_service_alerts
    rules:
      # External API Failures
      - alert: ExternalAPIFailures
        expr: increase(revoagent_external_api_failures_total[5m]) > 3
        for: 2m
        labels:
          severity: warning
          service: external_apis
        annotations:
          summary: "External API failures detected"
          description: "{{ $value }} external API failures for {{ $labels.service }} in the last 5 minutes"

      # Rate Limit Exceeded
      - alert: RateLimitExceeded
        expr: increase(revoagent_rate_limit_exceeded_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          service: rate_limiter
        annotations:
          summary: "Rate limit exceeded frequently"
          description: "Rate limit exceeded {{ $value }} times in the last 5 minutes"

  # Infrastructure Alerts
  - name: infrastructure_alerts
    rules:
      # Load Balancer Issues
      - alert: LoadBalancerDown
        expr: up{job="nginx"} == 0
        for: 30s
        labels:
          severity: critical
          service: nginx
        annotations:
          summary: "Load balancer is down"
          description: "NGINX load balancer is not responding"

      # Container Restart Loop
      - alert: ContainerRestartLoop
        expr: increase(container_restart_count[1h]) > 3
        for: 5m
        labels:
          severity: warning
          service: docker
        annotations:
          summary: "Container restart loop detected"
          description: "Container {{ $labels.name }} has restarted {{ $value }} times in the last hour"

      # High Network Traffic
      - alert: HighNetworkTraffic
        expr: rate(node_network_receive_bytes_total[5m]) > 100000000  # 100MB/s
        for: 10m
        labels:
          severity: warning
          service: network
        annotations:
          summary: "High network traffic detected"
          description: "Network receive rate is {{ $value | humanize }}B/s on {{ $labels.instance }}"

  # Security Alerts
  - name: security_alerts
    rules:
      # Suspicious Request Patterns
      - alert: SuspiciousRequestPattern
        expr: rate(revoagent_requests_total{status="429"}[5m]) > 1
        for: 2m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "High rate of rate-limited requests"
          description: "{{ $value }} rate-limited requests per second, possible attack"

      # Authentication Failures
      - alert: AuthenticationFailures
        expr: increase(revoagent_auth_failures_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "High authentication failure rate"
          description: "{{ $value }} authentication failures in the last 5 minutes"